apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hewo
  name: hewo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: hewo
  template:
    metadata:
      labels:
        run: hewo
    spec:
      containers:
      - image: thoschu/helloworld
        imagePullPolicy: Always
        name: hewo
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: POD_NUMBER_OF_CONTAINER
          valueFrom:
            fieldRef:
              fieldPath: "1"
      restartPolicy: Always
status:
  availableReplicas: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
