apiVersion: v1
kind: Service
metadata:
  labels:
    run: hewo
  name: hewo
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http-port
  selector:
    run: hewo
  type: NodePort
